"""added profile_image to User in models.py

Revision ID: 84723a8be9cf
Revises: 05dc8aaf724b
Create Date: 2023-03-07 16:48:03.985644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84723a8be9cf'
down_revision = '05dc8aaf724b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
